In [1]:
import tensorflow as tf

print(tf.__version__)

2.6.0


In [2]:
#tensorflow : 데이터 전처리, 데이터 모델링, 모델 제공을 위한 오픈소스 머신러닝 라이브러리

In [3]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
vector.ndim

1

In [7]:
# 일반적으로 tensorflow를 사용할 때 위에서처럼 직접 텐서를 만들지 x
# Tensorflow에 내장된 모듈인 tf.io나 tf.data가 데이터를 읽고 쓸 때 자동으로 데이터를 텐서로 변환한 다음 나중에 신경망 모델에 적용 및 처리

In [8]:
# scalar(스칼라)는 rank가 0인 tensor. ndim이 0이기 때문
# tensor는 dimension에 제한이 없다는 것이 중요

In [9]:
matrix = tf.constant(
    [
        [10, 7],
        [7, 10]
    ]

)
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [10]:
matrix.ndim

2

In [12]:
matrix2 = tf.constant(
    [
        [10., 7.],
        [7., 10,]
    ]
)
matrix2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float32)>

In [13]:
#tensorflow는 기본적으로 tensor를 생성할 때, 자료형(Datatype)을 int32나 float32로 설정

In [14]:
another_matrix = tf.constant(
    [
        [10., 7.],
        [3., 2.],
        [8., 9.]
    ],
    dtype = tf.float16
)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [15]:
another_matrix.ndim

2

In [16]:
tensor = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]

    ],
    [
        [13,14,15],
        [16,17,18]

    ]
])
tensor
# shape=(3, 2, 3) => 2행 3열짜리 행렬이 3개 있음. rank가 3인 tensor!

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [17]:
tensor.ndim

3

In [18]:
tf.dtypes

<module 'tensorflow._api.v2.dtypes' from 'c:\\Users\\kdh\\Desktop\\Language_Recognition\\Language_recognition\\20210821\\venv_210821\\lib\\site-packages\\tensorflow\\_api\\v2\\dtypes\\__init__.py'>

In [19]:
# 위에서 굳이 scalar, vector, matrix, tensor 등으로 구분해서 표현했지만, 기술적으로는 위 모든 것이 tensor

In [21]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [22]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [23]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [24]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [25]:
# tf.constant()를 사용해아핧지, tf.Variable()을 사용해야할지
# 우리가 해결할 문제에 따라서 선택하면 되고, 우리가 실제로 tensor를 직접 만들 경우 없음
# 왜? tensorflow가 데이터를 불러오고, 모델링할 때 알아서 선택해줌

In [29]:
random_1 = tf.random.Generator.from_seed(42) #np.random.seed(42)와 비슷
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

In [28]:
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [30]:
random_3 = tf.random.Generator.from_seed(42) #np.random.seed(42)
random_3 = random_3.normal(shape=(3,2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3,2))

In [32]:
random_3, random_4, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [33]:
# 왜 shuffle을 하는지
# 딥러닝 시 이미지가 15,000개 있을 때 처음에 10,000은 고양이, 5,000은 개
# 이 순서대로 학습을 하게 된다면 신경망에 overfit을 유발할 수 있음
not_shuffled = tf.constant([
    [10,7],
    [3,4],
    [2,5]
])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]])>

In [34]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [36]:
![](images/00-scalar-vector-matrix-tensor.png)

'[]'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.


In [37]:
# (224, 224, 3, 32)
# 224, 224 (첫부분 2차원) : 픽셀 단위로 이미지의 높이(height), 너비(width)
# 3: 이미지의 컬러 채널(RGB, Red Green Blue)
# 32 : 배치 크기(Batch Size) - 1번에 신경망이 처리할 이미지의 갯수

In [38]:
tf.ones(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [39]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [40]:
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32)
A = tf.constant(numpy_A, shape=[2,4,3])

numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]])>)

In [49]:
rank_4_tensor = tf.zeros([2, 3, 4, 5]) # (3, 4, 5) 2개
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [50]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [51]:
# tensor의 정보(shape, rank, size)를 얻는 과정
# shape : tensor를 이루는 각각 차원의 길이(element의 수)
# rank : tensor를 이루는 차원의 갯수(scalar는 0, vector : 1, matrix : 2, tensor : n(number))
# Axis or Dimension : tensor의 특정 차원 지칭
# Size : tensor 이루는 items(elements의 갯수)

In [52]:
print("모든 elements의 자료형은", rank_4_tensor.dtype)
print('차원의 갯수(rank)는', rank_4_tensor.ndim)
print('텐서의 shape는', rank_4_tensor.shape)
print('텐서의 axis 0에 속하는 element들은', rank_4_tensor.shape[0])
print('텐서의 axis 1에 속하는 elemenet들은', rank_4_tensor.shape[1])
print('텐서의 마지막 axis에 속하는 element들은', rank_4_tensor.shape[-1])
print('모든 element의 갯수 (2*3*4*5)는', tf.size(rank_4_tensor).numpy())

모든 elements의 자료형은 <dtype: 'float32'>
차원의 갯수(rank)는 4
텐서의 shape는 (2, 3, 4, 5)
텐서의 axis 0에 속하는 element들은 2
텐서의 axis 1에 속하는 elemenet들은 3
텐서의 마지막 axis에 속하는 element들은 5
모든 element의 갯수 (2*3*4*5)는 120


In [53]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [54]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [46]:
rank_2_tensor = tf.constant([
    [10, 7],
    [3,4]
])

In [47]:
# 각 행의 마지막 element 출력
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [48]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]])>)

In [55]:
tf.expand_dims(rank_2_tensor, axis = -1)
# axis = -1 / 마지막 차원이라는 뜻

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [56]:
tensor = tf.constant([
    [10, 7],
    [3, 4]
])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [57]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [58]:
tensor = tf.Variable([
    [10, 7],
    [3, 4]
])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [59]:
tensor


<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [60]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [61]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [62]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [63]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [64]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [65]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [66]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [67]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [68]:
# TensorFlow에서는 matrix multiplication을 tf.matmul()로 처리
# 파이썬에서는 @는 matrix multiplication을 의미하기도 함. @는 annotation을 의미하기도 함
# 규칙 1
# (3,5) @ (3,5) ==> 안됨

# 규칙 2 : 연산 결과 행렬은 외부 차원들로 이루어짐

In [69]:
tensor = tf.constant([
    [10, 7],
    [3, 4]
])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [70]:
# (2, 2) @ (2, 2)
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [71]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [72]:
X = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

Y = tf.constant([
    [7, 8],
    [9, 10],
    [11, 12]
])
X, Y, X.ndim, Y.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>,
 2,
 2)

In [73]:
# (3, 2) @ (3, 2) => 규칙 1 위반

X @ Y

InvalidArgumentError: In[0] mismatch In[1] shape: 2 vs. 3: [3,2] [3,2] 0 0 [Op:MatMul]

In [74]:
tf.matmul(X, Y)

InvalidArgumentError: In[0] mismatch In[1] shape: 2 vs. 3: [3,2] [3,2] 0 0 [Op:MatMul]

In [75]:
# 위와 같은 경우를 해결하려면
# (3, 2) @ (3, 2)
# 1) X의 shape 변경 => (2, 3) @ (3, 2) => 결과 (2, 2)
# 2) Y의 shape 변경 => (3, 2) @ (2, 3) => 결과 (3, 3)

In [76]:
tf.reshape(X, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [77]:
tf.reshape(X, shape=(2, 3)) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [78]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [79]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [80]:
X, tf.reshape(X, shape=(2, 3)), tf.transpose(X)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>)

In [81]:
tf.reshape(X, shape=(2, 3)) @ Y, tf.transpose(X) @ Y

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 58,  64],
        [139, 154]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]])>)

In [82]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [83]:
tf.matmul(a = X, b= Y, transpose_a = True, transpose_b = False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [84]:
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [85]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [86]:
tf.matmul(X, tf.reshape(Y, (2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [87]:
Y.shape, tf.reshape(Y, (2,3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [88]:
Y.shape, tf.reshape(Y, (2,3)), tf.transpose(Y)

(TensorShape([3, 2]),
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]])>)

In [89]:
B = tf.constant([1.7, 7,4])

In [90]:
C = tf.constant([1,7])

In [92]:
B, C

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.7, 7. , 4. ], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7])>)

In [93]:
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1.7, 7. , 4. ], dtype=float16)>

In [95]:
C = tf.cast(C, dtype=tf.float32)

In [96]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [97]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [98]:
E = tf.constant(np.random.randint(low=0, high=100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([62, 98, 82, 76,  5, 43, 86, 38, 76,  2,  7, 46, 30, 92, 66, 51, 75,
       20, 27,  8, 28, 17, 34, 89, 33, 58, 28, 72, 51, 48, 21, 87,  7, 36,
       52, 66, 82, 97, 13,  6, 21, 40, 48, 74, 41, 67, 63, 92, 68, 35])>

In [99]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [100]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [101]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=49>

In [102]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2464>

In [103]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=27.84>

In [106]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=775.5>

In [108]:
tf.argmax(E) # max  값을 가진 위치 알려줌

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [109]:
tf.argmin(E) # min 값을 가진 위치 알려줌

<tf.Tensor: shape=(), dtype=int64, numpy=9>

In [110]:
# ['RED', 'GREEN', 'BLUE'] : 우리가 보는 라벨
# [0.98, 0.01, 0.01] : softmax를 통해 고를 예측 확률 argmax

In [111]:
F = tf.constant(np.random.random(50))

In [112]:
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.58611319, 0.05207533, 0.08864623, 0.18289776, 0.83756968,
       0.83526677, 0.90415772, 0.57363082, 0.70824468, 0.65907522,
       0.21611477, 0.79856368, 0.44051647, 0.06838267, 0.29694578,
       0.1772932 , 0.94931319, 0.59979455, 0.08403366, 0.45987331,
       0.73641545, 0.01169458, 0.39105595, 0.66709241, 0.216945  ,
       0.96967144, 0.99745596, 0.10765187, 0.73265652, 0.16043985,
       0.37525881, 0.06972688, 0.70799079, 0.42371871, 0.54097451,
       0.98684186, 0.67828836, 0.20163796, 0.3839579 , 0.07004782,
       0.26800336, 0.75638653, 0.39215657, 0.50436847, 0.71621321,
       0.79181504, 0.5978176 , 0.23690296, 0.22258926, 0.5161777 ])>

In [113]:
tf.reduce_max(F), tf.argmax(F)

(<tf.Tensor: shape=(), dtype=float64, numpy=0.997455960864568>,
 <tf.Tensor: shape=(), dtype=int64, numpy=26>)

In [114]:
tf.reduce_min(F), tf.argmin(F)

(<tf.Tensor: shape=(), dtype=float64, numpy=0.011694580800425736>,
 <tf.Tensor: shape=(), dtype=int64, numpy=21>)

In [115]:
print(f'F의 최댓값 위치는 {tf.argmax(F).numpy()}')
print(f'F의 최댓값은 {tf.reduce_max(F).numpy()}')

F의 최댓값 위치는 26
F의 최댓값은 0.997455960864568


In [116]:
F[tf.argmax(F)].numpy()

0.997455960864568

In [117]:
print(f'tf.argmax()의 값을 이용해서 F의 최대값은 {F[tf.argmax(F)].numpy()}')
print(f'tf.reduce_max의 값과 tf.argmax()를 통해 찾은 값은 같을까 {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}')

tf.argmax()의 값을 이용해서 F의 최대값은 0.997455960864568
tf.reduce_max의 값과 tf.argmax()를 통해 찾은 값은 같을까 True


In [118]:
G = tf.constant(np.random.randint(0,100,50), shape=(1,1,1,1,50))
G, G.shape, G.ndim

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int32, numpy=
 array([[[[[66, 85, 88, 24,  0,  9, 54,  8, 86, 10, 28, 91, 44, 82, 78,
            23, 20,  7, 42, 47, 29, 47,  3, 81, 69, 45,  9, 72, 22, 15,
            65,  3, 14, 36, 48, 56, 33, 53, 54, 10, 63, 58, 66, 36,  2,
            36, 32, 28, 78, 75]]]]])>,
 TensorShape([1, 1, 1, 1, 50]),
 5)

In [119]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

In [120]:
some_list = [0, 1, 2, 3] # one-hot encoding으로 만드려고 한다
some_list

[0, 1, 2, 3]

In [122]:
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [124]:
tf.one_hot(some_list, depth=4, on_value='On', off_value='Off')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'On', b'Off', b'Off', b'Off'],
       [b'Off', b'On', b'Off', b'Off'],
       [b'Off', b'Off', b'On', b'Off'],
       [b'Off', b'Off', b'Off', b'On']], dtype=object)>

In [125]:
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [126]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [133]:
H = tf.cast(H, dtype=tf.float32)
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [129]:
H = tf.cast(H, dtype=tf.float32)
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [134]:
I = tf.Variable(np.arange(0,5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [135]:
I.assign([0,1,2,3,50])
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 0,  1,  2,  3, 50])>

In [136]:
I.assign_add([10, 10, 10, 10,10])
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([10, 11, 12, 13, 60])>

In [137]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [138]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [139]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [140]:
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_j = tf.constant([3., 7., 10.])
numpy_J, tensor_j

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 3.,  7., 10.], dtype=float32)>)

In [141]:
numpy_J.dtype, tensor_j.dtype

(tf.float64, tf.float32)

In [142]:
def function(x, y):
    return x ** 2 +y

In [143]:
x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [144]:
print(tf.config.list_physical_devices('GPU'))

[]


In [145]:
!nvidia-smi

'nvidia-smi'��(��) ���� �Ǵ� �ܺ� ����, ������ �� �ִ� ���α׷�, �Ǵ�
��ġ ������ �ƴմϴ�.


In [149]:
# 1. `tf.constant()`를 사용하여 선택한 값으로 벡터, 스칼라, 행렬 및 텐서를 생성합니다.
scalar = tf.constant(5)
vector = tf.constant([5, 10])
matrix = tf.constant([
    [1,2],
    [3,4]
])
tensor = tf.constant([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])


In [151]:
# 2. 1에서 생성한 텐서의 모양, 순위 및 크기를 찾습니다.
print(f"{scalar.shape} {scalar.ndim} {tf.size(scalar)}")
print(f"{vector.shape} {vector.ndim} {tf.size(vector)}")
print(f"{matrix.shape} {matrix.ndim} {tf.size(matrix)}")
print(f"{tensor.shape} {tensor.ndim} {tf.size(tensor)}")


() 0 1
(2,) 1 2
(2, 2) 2 4
(2, 2, 2) 3 8


In [161]:
# 3. shape가 `[5, 300]`인 0과 1 사이의 임의 값을 포함하는 두 개의 텐서를 만듭니다.
import numpy as np
X = tf.constant(np.random.randint(1500))
Y = tf.constant(np.random.randint(1500))
X = tf.constant(np.random.rand(1500), shape=(5, 300))
Y = tf.constant(np.random.rand(1500), shape=(5, 300))

In [162]:
#4. 행렬 곱을 사용하여 3에서 만든 두 텐서를 곱합니다.
X @ tf.reshape(Y, shape=(300, 5))
tf.transpose(X)@ Y
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(300, 300), dtype=float64, numpy=
array([[1.58945019, 0.89706498, 1.25935651, ..., 0.73099281, 1.21130804,
        1.32784255],
       [1.56022453, 1.7767218 , 1.20343581, ..., 1.15471936, 1.35320617,
        1.50759412],
       [1.7340868 , 1.32940856, 1.27036279, ..., 1.31262639, 1.75975504,
        1.31144655],
       ...,
       [1.1258547 , 1.00308717, 0.89288716, ..., 0.9539327 , 1.20629607,
        1.12726086],
       [1.56098539, 0.64682616, 1.29876249, ..., 0.90241647, 1.12637129,
        1.53420983],
       [1.85297761, 1.04130858, 1.4870312 , ..., 1.05817303, 1.31023951,
        1.69594435]])>

In [163]:
# 5. 내적을 사용하여 3에서 만든 두 개의 텐서를 곱합니다.

tf.tensordot(X, tf.transpose(Y), axes=1)
tf.tensordot(tf.transpose(x), Y, axes=1) 

InvalidArgumentError: cannot compute MatMul as input #1(zero-based) was expected to be a int32 tensor but is a double tensor [Op:MatMul]

In [159]:
# 6. shape가 `[224, 224, 3]`인 0과 1 사이의 임의 값으로 텐서를 만듭니다.
my_tensor = tf.constant(np.random.randint(0, 100 , 150528), shape=(224,224,3))
my_tensor , my_tensor.shape, my_tensor.ndim, tf.size(my_tensor)

(<tf.Tensor: shape=(224, 224, 3), dtype=int32, numpy=
 array([[[ 8, 28, 90],
         [ 8, 92, 73],
         [84, 64, 86],
         ...,
         [59, 22, 16],
         [ 4,  7, 54],
         [89, 27, 41]],
 
        [[ 4, 65, 64],
         [70, 62, 47],
         [27, 53,  8],
         ...,
         [55, 12, 31],
         [13, 66, 11],
         [48, 68, 68]],
 
        [[81, 24, 16],
         [22, 70, 62],
         [70, 45, 80],
         ...,
         [90, 82, 76],
         [99, 81, 80],
         [46, 13, 82]],
 
        ...,
 
        [[90, 14, 64],
         [82, 12, 93],
         [26, 22, 78],
         ...,
         [31, 26, 63],
         [32, 32, 69],
         [54, 67, 54]],
 
        [[57, 56,  7],
         [40, 76, 53],
         [97, 90, 13],
         ...,
         [92, 92, 90],
         [34, 92, 85],
         [79, 84, 32]],
 
        [[23, 52, 46],
         [23, 63, 12],
         [86, 43, 90],
         ...,
         [30, 58, 91],
         [ 8, 61, 38],
         [22, 53, 97]]])>,


In [160]:
#7. 6에서 생성한 텐서의 최소값과 최대값을 찾습니다.
tf.reduce_max(my_tensor), tf.reduce_min(my_tensor)
tf.argmax(my_tensor), tf.argmin(my_tensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=99>,
 <tf.Tensor: shape=(), dtype=int32, numpy=0>)

In [164]:
# 8. `[1, 224, 224, 3]` 모양의 임의 값으로 텐서를 만든 다음, 모양을 `[224, 224, 3]`으로 변경하도록 압축합니다.
my_tensor = tf.constant(np.random.randint(0, 200000, 150528), shape=(1, 224, 224, 3))
my_tensor.shape
my_tensor_squeezed = tf.squeeze(my_tensor)
my_tensor_squeezed.shape


TensorShape([224, 224, 3])

In [165]:
# 9. 자신이 선택한 값을 사용하여 `[10]` 모양의 텐서를 만든 다음 최대값을 갖는 인덱스를 찾습니다.
my_tensor = tf.constant(np.random.randint(0, 100, 10))
my_tensor.shape, my_tensor
tf.reduce_max(my_tensor).numpy(), tf.reduce_min(my_tensor).numpy()
tf.argmax(my_tensor).numpy(), tf.argmin(my_tensor).numpy() 
my_tensor[tf.argmax(my_tensor)].numpy(), my_tensor[tf.argmin(my_tensor)].numpy()

(99, 46)

In [166]:
# 10. 9에서 생성한 텐서를 원-핫 인코딩합니다.
tf.one_hot(my_tensor, depth=100)
tf.one_hot(my_tensor, depth=10, on_value="On", off_value="Off")

<tf.Tensor: shape=(10, 10), dtype=string, numpy=
array([[b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off',
        b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off',
        b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off',
        b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off',
        b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off',
        b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off',
        b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off',
        b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off',
        b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off',
        b'Off', b'Off'],
       [b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off', b'Off',
      