In [2]:
import numpy as np # as np는 거의 상용구처럼 사용

In [5]:
# numpy에서는 거의 대부분 array형태로 데이터를 처리

# 가장 간단히 numpy에서 array을 생성하는 방법
# 1. 파이썬 리스트를 전달해서 생성
c = np.array( [3, 4, 6] )
c, type(c), c.ndim

(array([3, 4, 6]), numpy.ndarray, 1)

In [6]:
# 2. 파이썬 튜플을 전달해서 생성
n = np.array( (4, 5, 7, 8, 9) )
n, type(n), n.ndim

(array([4, 5, 7, 8, 9]), numpy.ndarray, 1)

In [7]:
# 3. 숫자 1개만 전달해서 array 생성
z = np.array(4)
z, type(z), z.ndim

(array(4), numpy.ndarray, 0)

In [8]:
z1 = np.array([4])
z1, type(z1), z1.ndim

(array([4]), numpy.ndarray, 1)

In [12]:
type((4)), type((4, ))

(int, tuple)

In [11]:
z2 = np.array((4,))
z2, type(z2), z2.ndim

(array([4]), numpy.ndarray, 1)

In [14]:
# 4, 8, 9라는 내용을 가진 array만들어 보세요. array 이름 = c
c = np.array( (4, 8, 9) )
c, type(c), c.ndim

(array([4, 8, 9]), numpy.ndarray, 1)

In [15]:
c[1]

8

In [16]:
# 1차원 array 생성
y = np.array( [3, 6, 8, 9])
y.ndim

1

In [17]:
# 2차원 array 생성
y = np.array( [
    [4, 6, 7],
    [8, 1, 2]
])

In [18]:
y, y.ndim, type(y)

(array([[4, 6, 7],
        [8, 1, 2]]),
 2,
 numpy.ndarray)

In [19]:
print(y)

[[4 6 7]
 [8 1 2]]


In [29]:
# 3차원 array 생성
x = np.array([

    [
        [4, 6, 7],
        [8, 1, 2]
    ],
    [
        [4, 6, 7],
        [8, 1, 2]
    ],
    [
        [4, 6, 7],
        [8, 1, 2]
    ],    

])

In [30]:
x, x.ndim, type(x)

(array([[[4, 6, 7],
         [8, 1, 2]],
 
        [[4, 6, 7],
         [8, 1, 2]],
 
        [[4, 6, 7],
         [8, 1, 2]]]),
 3,
 numpy.ndarray)

In [31]:
print(x)

[[[4 6 7]
  [8 1 2]]

 [[4 6 7]
  [8 1 2]]

 [[4 6 7]
  [8 1 2]]]


In [32]:
# 자료형, array가 가진 데이터의 형태 => dtype (data type)
a = np.array( [3, 6, 7, 8] )

In [33]:
a, a.ndim, type(a)

(array([3, 6, 7, 8]), 1, numpy.ndarray)

In [34]:
a.dtype

dtype('int32')

In [35]:
b = np.array( [3, 6., 7, 8] )

In [36]:
b, b.ndim, type(b)

(array([3., 6., 7., 8.]), 1, numpy.ndarray)

In [37]:
b.dtype

dtype('float64')

In [39]:
a = np.array( [3, 6, 7, 8], dtype=float)
a.dtype

dtype('float64')

In [40]:
a

array([3., 6., 7., 8.])

In [41]:
a = np.array( [3, 6, 7, 8], dtype=complex)
a.dtype

dtype('complex128')

In [42]:
a

array([3.+0.j, 6.+0.j, 7.+0.j, 8.+0.j])

In [47]:
a = np.array([1, 2, 3, 4], dtype="i2")  # dtype을 바꿀 수 있게 이유는 무엇일까요?
# 메모리 사용의 효율성을 위해서 사용합니다.

In [48]:
a.dtype

dtype('int16')